apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-crud-deployment
  labels:
    app: ui-crud
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ui-crud
  template:
    metadata:
      labels:
        app: ui-crud
    spec:
      containers:
      - name: ui-crud
        image: 360162455068.dkr.ecr.eu-west-1.amazonaws.com/ui-crud:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
