apiVersion: v1
kind: Service
metadata:
  name: ui-crud-service
  labels:
    app: ui-crud
spec:
  selector:
    app: ui-crud
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020