apiVersion: v1
kind: Service
metadata:
  name: ui-crud-service
  labels:
    app: ui-crud
spec:
  selector:
    app: ui-crud
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30020